import { Credential } from 'payload/generated-types';

/** Fields that will be automatically generated by the system */
export const GENERATED_FIELDS = ['now', 'issuanceDate'];

/** Fields that are guaranteed to exist in templates */
export const GUARANTEED_FIELDS = [
    'earnerName',
    'credentialName',
    'emailAddress',
    ...GENERATED_FIELDS,
];

export const getCsvFieldsFromCredential = (credential: Credential): string[] => {
    const fields: string[] = [];

    if (credential.earnerName) fields.push('earnerName');
    if (credential.emailAddress) fields.push('emailAddress');
    if (credential.credentialName) fields.push('credentialName');

    if (credential.extraFields) {
        const extraFields = Object.keys(credential.extraFields).filter(field => {
            return Boolean(credential.extraFields[field]);
        });

        fields.push(...extraFields);
    }

    return fields;
};

export const credentialHasCsvField = (field: string, credential: Credential): boolean => {
    const credentialFields = getCsvFieldsFromCredential(credential);

    return credentialFields.includes(field);
};
