import { Credential } from 'payload/generated-types';

/** Fields that will be automatically generated by the system */
export const GENERATED_FIELDS = ['now', 'issuanceDate'];

/** Fields that will be automatically generated for eamils by the system */
export const GENERATED_EMAIL_FIELDS = ['link', ...GENERATED_FIELDS];

/** Fields that are required to exist in templates */
export const REQUIRED_FIELDS = ['earnerName', 'credentialName', 'emailAddress'];

/** Fields that are guaranteed to exist in templates */
export const GUARANTEED_FIELDS = [...REQUIRED_FIELDS, ...GENERATED_FIELDS];

/** Fields that are guaranteed to exist in email templates */
export const GUARANTEED_EMAIL_FIELDS = [...REQUIRED_FIELDS, ...GENERATED_EMAIL_FIELDS];

export const getCsvFieldsFromCredential = (credential: Credential): string[] => {
    const fields: string[] = [];

    if (credential.earnerName) fields.push('earnerName');
    if (credential.emailAddress) fields.push('emailAddress');
    if (credential.credentialName) fields.push('credentialName');

    if (credential.extraFields) {
        const extraFields = Object.keys(credential.extraFields).filter(field => {
            return Boolean(credential.extraFields[field]);
        });

        fields.push(...extraFields);
    }

    return fields;
};

export const credentialHasCsvField = (field: string, credential: Credential): boolean => {
    const credentialFields = getCsvFieldsFromCredential(credential);

    return credentialFields.includes(field);
};
